# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    published_date:

        # Filter name
        label: Date Added

        # Filter type
        type: daterange

        # SQL Conditions
        conditions: created_at >= ':after' AND created_at <= ':before'